version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - trees
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - trees
  nodeproxy:
    build: ./nodeproxy
    ports:
      - "8000:8000"
    networks:
      - trees
networks:
  trees:
    driver: bridge
