version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - trees
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BASE_API_URL_ENDPOINT=http://ipaddress:5000
      - REACT_APP_API_KEY=pk.eyJ1IjoiaGFycnlvY2xlaXJpZ2giLCJhIjoiY2xrcDg5MHg5MDdtZDNocDZmb3pnNGVpeSJ9.uBsz5pBfWmNRRRphtyNE9w
    networks:
      - trees
  nodeproxy:
    build: ./nodeproxy
    ports:
      - "8000:8000"
    networks:
      - trees
networks:
  trees:
    driver: bridge
